services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    depends_on:
      - loki
    ports:
      - "4317:4317"  # gRPC OTLP receiver
      - "4318:4318"  # HTTP OTLP receiver
      - "12345:12345" # Alloy internal metrics
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - loki
      - alloy
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
    - grafana-data:/var/lib/grafana
    - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

volumes:
  loki-data:
  grafana-data: